mappings:
  DMS: SilverStripeDMS\DMS
  DMSShortcodeHandler: SilverStripeDMS\DMSShortcodeHandler
  MigrateToDocumentSetsTask: SilverStripeDMS\Tasks\MigrateToDocumentSetsTask
  DMSJsonField: SilverStripeDMS\Forms\DMSJsonField
  DMSGridFieldAddNewButton: SilverStripeDMS\CMS\DMSGridFieldAddNewButton
  DMSUploadField_ItemHandler: SilverStripeDMS\CMS\DMSUploadField_ItemHandler
  DMSGridFieldEditButton: SilverStripeDMS\CMS\DMSGridFieldEditButton
  DMSDocumentAddExistingField: SilverStripeDMS\CMS\DMSDocumentAddExistingField
  DocumentHTMLEditorFieldToolbar: SilverStripeDMS\CMS\DocumentHTMLEditorFieldToolbar
  DMSDocumentAddController: SilverStripeDMS\CMS\DMSDocumentAddController
  DMSUploadField: SilverStripeDMS\CMS\DMSUploadField
  DMSDocumentAdmin: SilverStripeDMS\CMS\DMSDocumentAdmin
  DMSGridFieldDetailForm_ItemRequest: SilverStripeDMS\CMS\DMSGridFieldDetailForm_ItemRequest
  DMSInterface: SilverStripeDMS\Interface\DMSInterface
  DMSDocumentInterface: SilverStripeDMS\Interface\DMSDocumentInterface
  DMSDocumentTaxonomyExtension: SilverStripeDMS\Extensions\DMSDocumentTaxonomyExtension
  DMSTaxonomyTypeExtension: SilverStripeDMS\Extensions\DMSTaxonomyTypeExtension
  DMSSiteTreeExtension: SilverStripeDMS\Extensions\DMSSiteTreeExtension
  FileNotFoundException: SilverStripeDMS\Exceptions\FileNotFoundException
  DMSDocument_versions: SilverStripeDMS\Model\DMSDocument_versions
  DMSDocument: SilverStripeDMS\Model\DMSDocument
  DMSDocumentController: SilverStripeDMS\Control\DMSDocumentController
  DMSDocumentSet: SilverStripeDMS\Model\DMSDocumentSet
  ShortCodeRelationFinder: SilverStripeDMS\Tools\ShortCodeRelationFinder