---
Name: dmsconfig
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Innoweb\DMS\Extensions\DMSSiteTreeExtension
  documents_enabled: true
SilverStripe\Assets\File:
  extensions:
    - Innoweb\DMS\Extensions\FileExtension
SilverStripe\AssetAdmin\Forms\FileFormFactory:
  extensions:
    - Innoweb\DMS\Extensions\FormFactoryExtension
  